# Nom de l'application
spring.application.name=assurance-app

# Base de données H2 (en mémoire, pour les tests)
spring.datasource.url=jdbc:h2:mem:assurancedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Activer la console H2 (accessible sur /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Port du serveur
server.port=8080